---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
spec:
  address: https://vault.awsdevopstrainers.info

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: dynamic-secrets-pull-role
    serviceAccount: dynamic-secrets-pull-sa

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-artifactory-token
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: artifactory-secret
  destination:
    create: true
    name: artifactory-secret
    type: Opaque
  refreshAfter: 5m
