apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory
    targetRevision: 107.161.15
    helm:
      values: |
        global:
          masterKeySecretName: artifactory-mandatory-keys
          joinKeySecretName: artifactory-mandatory-keys

        artifactory:
          persistence:
            enabled: true
            type: pvc
            size: 2Gi
            storageClassName: ebs-csi-default-sc

        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: true
              size: 1Gi
              storageClass: ebs-csi-default-sc

        nginx:
          enabled: false

        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: artifactory

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true