apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-app
  namespace: argocd
spec:
  project: default     
  source:
    chart: argo-cd
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.21.1
    helm:
      values: |
        image:
          repository: registry.k8s.io/external-dns/external-dns
     
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true