---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - ebs-csi-driver.yaml.yaml
  - external-dns.yaml
  - vault.yaml
  - artifactory.yaml
  - external-secrets.yaml