---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

  # ebs csi driver
  - ebs-csi-driver/ebs-csi-driver-app.yaml

  # external dns
  - external-dns/external-dns-app.yaml

  # artifactory
  - artifactory/artifactory-app.yaml

  # external secret operator
  - external-secret-operator/external-secrets-app.yaml
  - external-secret-operator/external-secrets-operator.yaml
  - external-secret-operator/dynamic-secret-pull.yaml

  # vault
  - vault/vault-app.yaml

  # vault secret operator
  - vault-secret-operator/vault-secret-operator-app.yaml
  - vault-secret-operator/dynamic-secret-pull.yaml
