---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml

  # Applications
  - external-dns
  - external-secret-operator
  - ebs-csi-driver
  - artifactory
  - vault-app

  # - vault-secret-operator/vault-secret-operator-app.yaml
  # - vault-secret-operator/dynamic-secret-pull.yaml
