apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: vault-secret-store
  namespace: argocd

spec:
  provider:
    vault:
      server: https://vault.awsdevopstrainers.info
      path: kv
      version: v1

      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets-role
          serviceAccountRef:
            name: external-secrets-vault
