---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: artifactory-token
spec:
  vaultAuthRef: default
  mount: kv
  type: kv-v2
  path: artifactory-secret

  destination:
    create: true
    name: artifactory-dynamic-secret

  renewalPercent: 67