apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-artifactory-docker-secret
spec:
  vaultAuthRef: default
  mount: kv
  type: kv-v2
  path: docker/config

  destination:
    create: true
    name: regcred
    type: kubernetes.io/dockerconfigjson

  refreshAfter: 5m
  transformation:
    templates:
      .dockerconfigjson: |
        {
          "auths": {
            "artifactory.awsdevopstrainers.info": {
              "username": "admin",
              "password": "{{ .artifactoryToken }}",
              "auth": "{{ printf "admin:%s" .artifactoryToken | b64enc }}"
            }
          }
        }