apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory
    targetRevision: 107.161.15

    helm:
      values: |
        global:
          masterKeySecretName: artifactory-mandatory-keys
          joinKeySecretName: artifactory-mandatory-keys

        artifactory:
          replicaCount: 1

          resources:
            requests:
              cpu: 2
              memory: 8Gi
            limits:
              cpu: 4
              memory: 8Gi

          persistence:
            enabled: true
            type: file-system
            size: 20Gi
            storageClassName: ebs-csi-default-sc

        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: true
              size: 10Gi
              storageClass: ebs-csi-default-sc

        nginx:
          enabled: false

        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: artifactory

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
