apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dynamic-artifactory-secret-store
  namespace: argocd
spec:
  provider:
    vault:
      server: https://vault.awsdevopstrainers.info
      path: artifactory
      version: v1
      auth:
        iam:
          path: aws
          vaultRole: eso-role

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifactory-token
  namespace: argocd
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: dynamic-artifactory-secret-store
    kind: SecretStore
  target:
    name: artifactory-token
    creationPolicy: Owner
  data:
    - secretKey: access_token
      remoteRef:
        key: token/devops
        property: access_token