---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-static-secret-store
  namespace: argocd
spec:
  provider:
    vault:
      server: https://vault.awsdevopstrainers.info
      path: kv
      version: v2
      auth:
        iam:
          path: aws
          vaultRole: eso-role

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifactory-docker-secret
  namespace: argocd
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: vault-static-secret-store
    kind: SecretStore
  target:
    name: artifactory-docker-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "artifactory.awsdevopstrainers.info": {
                "username": "admin",
                "password": "{{ .token }}",
                "auth": "{{ printf "admin:%s" .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: token
      remoteRef:
        key: artifactory/data
        property: token
