---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-static-secret-store
  namespace: argocd
spec:
  provider:
    vault:
      server: https://vault.awsdevopstrainers.info
      path: kv
      version: v2
      auth:
        iam:
          path: aws
          vaultRole: eso-role

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-database-creds
  namespace: argocd
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: vault-static-secret-store
    kind: SecretStore
  target:
    name: mysql-credentials
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: mysql-db-creds
        property: username

    - secretKey: password
      remoteRef:
        key: mysql-db-creds
        property: password
